title: How do CATs process Markdown files? 
description: A study of how Computer Aided Translation programs import and export Markdown files
theme: just-the-docs

url: https://pj-woz.github.io/cats-vs-markdown

aux_links:
  Project repository: https://github.com/pj-woz/cats-vs-markdown

footer_content: "&#169; Paweł Woźnikowski, 2023"

logo: "resources/images/logo-v2-1.png"

favicon_ico: "/resources/images/favicon.ico"

back_to_top: true

back_to_top_text: "Back to top"

heading_anchors: true